//! Render `Dedicated` virtual gateways as their own Octopus workloads.
//!
//! A virtual gateway with `isolation: Dedicated` runs as a separate Octopus
//! Deployment reached **directly** (its own `LoadBalancer` Service) — never
//! proxied through the edge — which preserves the single-hop invariant. This
//! reconciler renders the child `ConfigMap` + `Deployment` + `Service` and
//! server-side-applies them (or deletes them when a gateway is removed or
//! downgraded to `Shared`).

use crate::crds::OctopusGatewaySpec;
use crate::{K8sError, Result};
use k8s_openapi::api::apps::v1::{Deployment, DeploymentSpec};
use k8s_openapi::api::core::v1::{
    ConfigMap, ConfigMapVolumeSource, Container, ContainerPort, PodSpec, PodTemplateSpec, Service,
    ServicePort, ServiceSpec, Volume, VolumeMount,
};
use k8s_openapi::apimachinery::pkg::apis::meta::v1::{LabelSelector, ObjectMeta};
use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;
use kube::api::{Api, DeleteParams, Patch, PatchParams};
use kube::Client;
use std::collections::BTreeMap;

const FIELD_MANAGER: &str = "octopus-operator";
const CONFIG_MOUNT_PATH: &str = "/etc/octopus";
const CONFIG_FILE: &str = "octopus.yaml";
const DEFAULT_LISTEN_PORT: i32 = 8080;

/// The child workload name for a dedicated `gateway`.
pub fn child_name(gateway: &str) -> String {
    format!("octopus-vgw-{gateway}")
}

/// Standard labels identifying a dedicated gateway's child objects (also the
/// Deployment selector and pod labels).
fn child_labels(gateway: &str) -> BTreeMap<String, String> {
    BTreeMap::from([
        ("app.kubernetes.io/name".to_string(), child_name(gateway)),
        (
            "app.kubernetes.io/managed-by".to_string(),
            "octopus-operator".to_string(),
        ),
        (
            "gateway.octopus.io/dedicated-for".to_string(),
            gateway.to_string(),
        ),
    ])
}

/// Container/Service port parsed from a `host:port` listen address.
fn listen_port(listen: &str) -> i32 {
    listen
        .rsplit(':')
        .next()
        .and_then(|p| p.parse().ok())
        .unwrap_or(DEFAULT_LISTEN_PORT)
}

/// Render the child Octopus config stored in the ConfigMap. The child runs in
/// Kubernetes mode and serves ONLY this gateway's routes (`serve_only_gateway`),
/// so it never re-renders dedicated children.
fn render_child_config(gateway: &str, spec: &OctopusGatewaySpec) -> String {
    format!(
        "# Generated by octopus-operator for a Dedicated virtual gateway.\n\
         # Hostnames: {hostnames}\n\
         gateway:\n  listen: \"{listen}\"\n\
         kubernetes:\n  enabled: true\n  gateway_class: \"{class}\"\n  serve_only_gateway: \"{gateway}\"\n",
        hostnames = spec.hostnames.join(", "),
        listen = spec.listen,
        class = spec.gateway_class_name.as_deref().unwrap_or("octopus"),
    )
}

/// Render the ConfigMap holding the child's generated `octopus.yaml`.
pub fn render_configmap(gateway: &str, namespace: &str, spec: &OctopusGatewaySpec) -> ConfigMap {
    ConfigMap {
        metadata: ObjectMeta {
            name: Some(child_name(gateway)),
            namespace: Some(namespace.to_string()),
            labels: Some(child_labels(gateway)),
            ..Default::default()
        },
        data: Some(BTreeMap::from([(
            CONFIG_FILE.to_string(),
            render_child_config(gateway, spec),
        )])),
        ..Default::default()
    }
}

/// Render the child Octopus Deployment.
pub fn render_deployment(
    gateway: &str,
    namespace: &str,
    image: &str,
    spec: &OctopusGatewaySpec,
) -> Deployment {
    let name = child_name(gateway);
    let labels = child_labels(gateway);
    let port = listen_port(&spec.listen);
    Deployment {
        metadata: ObjectMeta {
            name: Some(name.clone()),
            namespace: Some(namespace.to_string()),
            labels: Some(labels.clone()),
            ..Default::default()
        },
        spec: Some(DeploymentSpec {
            replicas: Some(1),
            selector: LabelSelector {
                match_labels: Some(labels.clone()),
                ..Default::default()
            },
            template: PodTemplateSpec {
                metadata: Some(ObjectMeta {
                    labels: Some(labels.clone()),
                    ..Default::default()
                }),
                spec: Some(PodSpec {
                    containers: vec![Container {
                        name: "octopus".to_string(),
                        image: Some(image.to_string()),
                        args: Some(vec![
                            "--config".to_string(),
                            format!("{CONFIG_MOUNT_PATH}/{CONFIG_FILE}"),
                        ]),
                        ports: Some(vec![ContainerPort {
                            container_port: port,
                            ..Default::default()
                        }]),
                        volume_mounts: Some(vec![VolumeMount {
                            name: "config".to_string(),
                            mount_path: CONFIG_MOUNT_PATH.to_string(),
                            read_only: Some(true),
                            ..Default::default()
                        }]),
                        ..Default::default()
                    }],
                    volumes: Some(vec![Volume {
                        name: "config".to_string(),
                        config_map: Some(ConfigMapVolumeSource {
                            name: name.clone(),
                            ..Default::default()
                        }),
                        ..Default::default()
                    }]),
                    ..Default::default()
                }),
            },
            ..Default::default()
        }),
        ..Default::default()
    }
}

/// Render the child Service. Type `LoadBalancer` so the gateway's hostname
/// resolves straight to the child pod — the edge is bypassed (single hop).
pub fn render_service(gateway: &str, namespace: &str, spec: &OctopusGatewaySpec) -> Service {
    let labels = child_labels(gateway);
    let port = listen_port(&spec.listen);
    Service {
        metadata: ObjectMeta {
            name: Some(child_name(gateway)),
            namespace: Some(namespace.to_string()),
            labels: Some(labels.clone()),
            ..Default::default()
        },
        spec: Some(ServiceSpec {
            type_: Some("LoadBalancer".to_string()),
            selector: Some(labels),
            ports: Some(vec![ServicePort {
                port,
                target_port: Some(IntOrString::Int(port)),
                ..Default::default()
            }]),
            ..Default::default()
        }),
        ..Default::default()
    }
}

/// Reconciles `Dedicated` virtual gateways into directly-reachable child Octopus
/// workloads. Held by the operator only on the replica that owns writes (leader).
#[derive(Clone)]
pub struct DedicatedGatewayReconciler {
    client: Client,
    /// Container image used for child Octopus deployments.
    image: String,
}

impl std::fmt::Debug for DedicatedGatewayReconciler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DedicatedGatewayReconciler")
            .field("image", &self.image)
            .finish()
    }
}

impl DedicatedGatewayReconciler {
    /// Create a reconciler that renders child deployments using `image`.
    pub fn new(client: Client, image: String) -> Self {
        Self { client, image }
    }

    /// Server-side-apply the child ConfigMap + Deployment + Service for a
    /// dedicated gateway (idempotent; safe to call repeatedly).
    pub async fn reconcile(
        &self,
        gateway: &str,
        namespace: &str,
        spec: &OctopusGatewaySpec,
    ) -> Result<()> {
        let pp = PatchParams::apply(FIELD_MANAGER).force();
        let name = child_name(gateway);

        let cm = render_configmap(gateway, namespace, spec);
        Api::<ConfigMap>::namespaced(self.client.clone(), namespace)
            .patch(&name, &pp, &Patch::Apply(&cm))
            .await
            .map_err(|e| K8sError::Apply(e.to_string()))?;

        let dep = render_deployment(gateway, namespace, &self.image, spec);
        Api::<Deployment>::namespaced(self.client.clone(), namespace)
            .patch(&name, &pp, &Patch::Apply(&dep))
            .await
            .map_err(|e| K8sError::Apply(e.to_string()))?;

        let svc = render_service(gateway, namespace, spec);
        Api::<Service>::namespaced(self.client.clone(), namespace)
            .patch(&name, &pp, &Patch::Apply(&svc))
            .await
            .map_err(|e| K8sError::Apply(e.to_string()))?;

        tracing::info!(gateway = %gateway, namespace = %namespace, "Dedicated gateway workload reconciled");
        Ok(())
    }

    /// Delete the child workload for a gateway (on delete or downgrade to
    /// `Shared`). Missing objects are ignored.
    pub async fn delete(&self, gateway: &str, namespace: &str) -> Result<()> {
        let name = child_name(gateway);
        let dp = DeleteParams::default();
        let _ = Api::<Service>::namespaced(self.client.clone(), namespace)
            .delete(&name, &dp)
            .await;
        let _ = Api::<Deployment>::namespaced(self.client.clone(), namespace)
            .delete(&name, &dp)
            .await;
        let _ = Api::<ConfigMap>::namespaced(self.client.clone(), namespace)
            .delete(&name, &dp)
            .await;
        tracing::info!(gateway = %gateway, namespace = %namespace, "Dedicated gateway workload deleted");
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crds::GatewayIsolation;

    fn spec(hostnames: &[&str], listen: &str) -> OctopusGatewaySpec {
        OctopusGatewaySpec {
            listen: listen.to_string(),
            gateway_class_name: None,
            default_auth_provider: None,
            hostnames: hostnames.iter().map(ToString::to_string).collect(),
            default_policy: None,
            isolation: GatewayIsolation::Dedicated,
            farp_binding: false,
        }
    }

    #[test]
    fn child_name_is_prefixed() {
        assert_eq!(child_name("tenant-big"), "octopus-vgw-tenant-big");
    }

    #[test]
    fn listen_port_parses_or_defaults() {
        assert_eq!(listen_port("0.0.0.0:8080"), 8080);
        assert_eq!(listen_port("0.0.0.0:443"), 443);
        assert_eq!(listen_port("garbage"), DEFAULT_LISTEN_PORT);
    }

    #[test]
    fn configmap_carries_generated_octopus_yaml() {
        let cm = render_configmap(
            "big",
            "octopus-system",
            &spec(&["big.twinos.cloud"], "0.0.0.0:8080"),
        );
        assert_eq!(cm.metadata.name.as_deref(), Some("octopus-vgw-big"));
        let yaml = cm.data.unwrap().remove(CONFIG_FILE).unwrap();
        assert!(yaml.contains("0.0.0.0:8080"), "listen address present");
        assert!(yaml.contains("big.twinos.cloud"), "hostname present");
        assert!(yaml.contains("enabled: true"), "kubernetes mode enabled");
        assert!(
            yaml.contains("serve_only_gateway: \"big\""),
            "child scoped to its own gateway"
        );
    }

    #[test]
    fn deployment_runs_octopus_image_with_config_mount() {
        let dep = render_deployment(
            "big",
            "ns",
            "ghcr.io/xraph/octopus:1.2.3",
            &spec(&[], "0.0.0.0:443"),
        );
        let dspec = dep.spec.unwrap();
        // selector matches pod template labels (else the Deployment is invalid)
        assert_eq!(
            dspec.selector.match_labels,
            dspec.template.metadata.unwrap().labels
        );
        let container = &dspec.template.spec.unwrap().containers[0];
        assert_eq!(
            container.image.as_deref(),
            Some("ghcr.io/xraph/octopus:1.2.3")
        );
        assert_eq!(
            container.args.as_ref().unwrap(),
            &vec![
                "--config".to_string(),
                "/etc/octopus/octopus.yaml".to_string()
            ]
        );
        assert_eq!(container.ports.as_ref().unwrap()[0].container_port, 443);
    }

    #[test]
    fn service_is_loadbalancer_for_direct_routing() {
        let svc = render_service("big", "ns", &spec(&[], "0.0.0.0:8080"));
        let sspec = svc.spec.unwrap();
        assert_eq!(sspec.type_.as_deref(), Some("LoadBalancer"));
        assert_eq!(sspec.ports.unwrap()[0].port, 8080);
        // selector targets the child pods
        assert_eq!(
            sspec
                .selector
                .unwrap()
                .get("gateway.octopus.io/dedicated-for"),
            Some(&"big".to_string())
        );
    }
}
