//! Router configuration for the admin dashboard

use axum::{
    routing::{delete, get, post, put},
    Router,
};
use std::sync::Arc;
use tower_http::services::{ServeDir, ServeFile};

use crate::api_handlers::*;
use crate::handlers::*;

/// Dashboard router builder
pub struct DashboardRouter;

impl DashboardRouter {
    /// Build the dashboard router
    #[must_use]
    pub fn build(state: Arc<AppState>) -> Router {
        // UI distribution path
        let ui_dist = concat!(env!("CARGO_MANIFEST_DIR"), "/ui/dist");
        
        Router::new()
            // ===== Server-rendered pages (Askama templates) =====
            .route("/admin", get(overview_handler))
            .route("/admin/routes", get(routes_handler))
            .route("/admin/health", get(health_handler))
            .route("/admin/plugins", get(plugins_handler))
            .route("/admin/analytics", get(analytics_handler))
            .route("/admin/logs", get(logs_handler))
            .route("/admin/config", get(config_handler))
            
            // ===== Metrics & Analytics API =====
            .route("/admin/api/stats", get(api_stats_handler))
            .route("/admin/api/analytics", get(api_analytics_handler))
            .route("/admin/api/metrics/realtime", get(api_realtime_metrics_handler))
            .route("/admin/api/metrics/timeseries", get(api_timeseries_handler))
            .route("/admin/api/metrics/performance", get(api_performance_metrics_handler))
            
            // ===== Routes Management API (CRUD) =====
            .route("/admin/api/routes", get(api_routes_list_handler))
            .route("/admin/api/routes", post(api_route_create_handler))
            .route("/admin/api/routes/:id", get(api_route_get_handler))
            .route("/admin/api/routes/:id", put(api_route_update_handler))
            .route("/admin/api/routes/:id", delete(api_route_delete_handler))
            
            // ===== Plugin Management API =====
            .route("/admin/api/plugins", get(api_plugins_list_handler))
            .route("/admin/api/plugins/:id", get(api_plugin_get_handler))
            .route("/admin/api/plugins/:id/toggle", post(api_plugin_toggle_handler))
            .route("/admin/api/plugins/:id/config", put(api_plugin_config_handler))
            
            // ===== Logs & Monitoring API =====
            .route("/admin/api/logs", get(api_logs_handler))
            .route("/admin/api/activity", get(api_activity_handler))
            .route("/admin/api/health", get(api_health_handler))
            .route("/admin/api/security/events", get(api_security_events_handler))
            
            // ===== Configuration Management API =====
            .route("/admin/api/config", get(api_config_list_handler))
            .route("/admin/api/config/:key", put(api_config_update_handler))
            
            // ===== System Information API =====
            .route("/admin/api/system/info", get(api_system_info_handler))
            
            // ===== Static assets =====
            .nest_service(
                "/admin/static",
                ServeDir::new(concat!(env!("CARGO_MANIFEST_DIR"), "/static"))
            )
            
            // ===== Next.js React UI (optional SPA) =====
            // Structure generated by Next.js:
            //   - /_next/static/chunks/*.js    - JavaScript chunks
            //   - /_next/static/media/*        - Fonts, images
            //   - /overview/index.html         - Pre-rendered pages
            //   - /routes/index.html
            //   - /health/index.html
            //   - /plugins/index.html
            //   - /index.html                  - Landing page
            .nest_service(
                "/admin/ui",
                ServeDir::new(ui_dist)
                    .append_index_html_on_directories(true)
                    .not_found_service(ServeFile::new(format!("{}/index.html", ui_dist)))
                    .precompressed_gzip()
                    .precompressed_br()
            )
            .with_state(state)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::http::StatusCode;
    use tower::ServiceExt;

    #[tokio::test]
    async fn test_router() {
        let state = Arc::new(AppState::new());
        let app = DashboardRouter::build(state);

        let response = app
            .oneshot(
                axum::http::Request::builder()
                    .uri("/admin")
                    .body(axum::body::Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::OK);
    }
}

